# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b9063352ad2f9b244f34ab38b3ca4fc72443c8c3ed6bea2660dd5a2808d73e641f59adaafc0bd61561deaef7c59af6b760ca1c17db058139a5ec49e02f8780a

test:
  secret_key_base: 510991d056bb5bb91392ca0da8889f8426cb6d7689d5980482a7ac632d3979eb0adf578bf4873ad3d80b7617bef90a0adf5f5388edf9af59123be7e67fec1e36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
